// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FractionalInfoService.proto

package com.thinking.grpc.proto;

public final class StuFractionalProto {
  private StuFractionalProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetFractionalInfoReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetFractionalInfoReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string place = 1;</code>
     */
    boolean hasPlace();
    /**
     * <code>required string place = 1;</code>
     */
    java.lang.String getPlace();
    /**
     * <code>required string place = 1;</code>
     */
    com.google.protobuf.ByteString
        getPlaceBytes();

    /**
     * <code>required string type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 2;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 2;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * Protobuf type {@code GetFractionalInfoReq}
   */
  public  static final class GetFractionalInfoReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetFractionalInfoReq)
      GetFractionalInfoReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetFractionalInfoReq.newBuilder() to construct.
    private GetFractionalInfoReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetFractionalInfoReq() {
      place_ = "";
      type_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetFractionalInfoReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetFractionalInfoReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              place_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              type_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thinking.grpc.proto.StuFractionalProto.internal_static_GetFractionalInfoReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thinking.grpc.proto.StuFractionalProto.internal_static_GetFractionalInfoReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq.class, com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq.Builder.class);
    }

    private int bitField0_;
    public static final int PLACE_FIELD_NUMBER = 1;
    private volatile java.lang.Object place_;
    /**
     * <code>required string place = 1;</code>
     */
    public boolean hasPlace() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string place = 1;</code>
     */
    public java.lang.String getPlace() {
      java.lang.Object ref = place_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          place_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string place = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPlaceBytes() {
      java.lang.Object ref = place_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        place_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object type_;
    /**
     * <code>required string type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string type = 2;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPlace()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, place_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, place_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq)) {
        return super.equals(obj);
      }
      com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq other = (com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq) obj;

      if (hasPlace() != other.hasPlace()) return false;
      if (hasPlace()) {
        if (!getPlace()
            .equals(other.getPlace())) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (!getType()
            .equals(other.getType())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPlace()) {
        hash = (37 * hash) + PLACE_FIELD_NUMBER;
        hash = (53 * hash) + getPlace().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetFractionalInfoReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetFractionalInfoReq)
        com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.thinking.grpc.proto.StuFractionalProto.internal_static_GetFractionalInfoReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.thinking.grpc.proto.StuFractionalProto.internal_static_GetFractionalInfoReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq.class, com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq.Builder.class);
      }

      // Construct using com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        place_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.thinking.grpc.proto.StuFractionalProto.internal_static_GetFractionalInfoReq_descriptor;
      }

      @java.lang.Override
      public com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq getDefaultInstanceForType() {
        return com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq build() {
        com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq buildPartial() {
        com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq result = new com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.place_ = place_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq) {
          return mergeFrom((com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq other) {
        if (other == com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq.getDefaultInstance()) return this;
        if (other.hasPlace()) {
          bitField0_ |= 0x00000001;
          place_ = other.place_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000002;
          type_ = other.type_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasPlace()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object place_ = "";
      /**
       * <code>required string place = 1;</code>
       */
      public boolean hasPlace() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string place = 1;</code>
       */
      public java.lang.String getPlace() {
        java.lang.Object ref = place_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            place_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string place = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPlaceBytes() {
        java.lang.Object ref = place_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          place_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string place = 1;</code>
       */
      public Builder setPlace(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        place_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string place = 1;</code>
       */
      public Builder clearPlace() {
        bitField0_ = (bitField0_ & ~0x00000001);
        place_ = getDefaultInstance().getPlace();
        onChanged();
        return this;
      }
      /**
       * <code>required string place = 1;</code>
       */
      public Builder setPlaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        place_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string type = 2;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 2;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 2;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetFractionalInfoReq)
    }

    // @@protoc_insertion_point(class_scope:GetFractionalInfoReq)
    private static final com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq();
    }

    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GetFractionalInfoReq>
        PARSER = new com.google.protobuf.AbstractParser<GetFractionalInfoReq>() {
      @java.lang.Override
      public GetFractionalInfoReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetFractionalInfoReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetFractionalInfoReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetFractionalInfoReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetFractionalInfoRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetFractionalInfoResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string place = 1;</code>
     */
    boolean hasPlace();
    /**
     * <code>required string place = 1;</code>
     */
    java.lang.String getPlace();
    /**
     * <code>required string place = 1;</code>
     */
    com.google.protobuf.ByteString
        getPlaceBytes();

    /**
     * <code>required string type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 2;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 2;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>required float fractional = 3;</code>
     */
    boolean hasFractional();
    /**
     * <code>required float fractional = 3;</code>
     */
    float getFractional();
  }
  /**
   * Protobuf type {@code GetFractionalInfoResp}
   */
  public  static final class GetFractionalInfoResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetFractionalInfoResp)
      GetFractionalInfoRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetFractionalInfoResp.newBuilder() to construct.
    private GetFractionalInfoResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetFractionalInfoResp() {
      place_ = "";
      type_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetFractionalInfoResp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetFractionalInfoResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              place_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              type_ = bs;
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              fractional_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thinking.grpc.proto.StuFractionalProto.internal_static_GetFractionalInfoResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thinking.grpc.proto.StuFractionalProto.internal_static_GetFractionalInfoResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp.class, com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp.Builder.class);
    }

    private int bitField0_;
    public static final int PLACE_FIELD_NUMBER = 1;
    private volatile java.lang.Object place_;
    /**
     * <code>required string place = 1;</code>
     */
    public boolean hasPlace() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string place = 1;</code>
     */
    public java.lang.String getPlace() {
      java.lang.Object ref = place_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          place_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string place = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPlaceBytes() {
      java.lang.Object ref = place_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        place_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object type_;
    /**
     * <code>required string type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string type = 2;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FRACTIONAL_FIELD_NUMBER = 3;
    private float fractional_;
    /**
     * <code>required float fractional = 3;</code>
     */
    public boolean hasFractional() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required float fractional = 3;</code>
     */
    public float getFractional() {
      return fractional_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPlace()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFractional()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, place_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeFloat(3, fractional_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, place_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, fractional_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp)) {
        return super.equals(obj);
      }
      com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp other = (com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp) obj;

      if (hasPlace() != other.hasPlace()) return false;
      if (hasPlace()) {
        if (!getPlace()
            .equals(other.getPlace())) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (!getType()
            .equals(other.getType())) return false;
      }
      if (hasFractional() != other.hasFractional()) return false;
      if (hasFractional()) {
        if (java.lang.Float.floatToIntBits(getFractional())
            != java.lang.Float.floatToIntBits(
                other.getFractional())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPlace()) {
        hash = (37 * hash) + PLACE_FIELD_NUMBER;
        hash = (53 * hash) + getPlace().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      if (hasFractional()) {
        hash = (37 * hash) + FRACTIONAL_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getFractional());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetFractionalInfoResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetFractionalInfoResp)
        com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.thinking.grpc.proto.StuFractionalProto.internal_static_GetFractionalInfoResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.thinking.grpc.proto.StuFractionalProto.internal_static_GetFractionalInfoResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp.class, com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp.Builder.class);
      }

      // Construct using com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        place_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        fractional_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.thinking.grpc.proto.StuFractionalProto.internal_static_GetFractionalInfoResp_descriptor;
      }

      @java.lang.Override
      public com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp getDefaultInstanceForType() {
        return com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp.getDefaultInstance();
      }

      @java.lang.Override
      public com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp build() {
        com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp buildPartial() {
        com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp result = new com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.place_ = place_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.fractional_ = fractional_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp) {
          return mergeFrom((com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp other) {
        if (other == com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp.getDefaultInstance()) return this;
        if (other.hasPlace()) {
          bitField0_ |= 0x00000001;
          place_ = other.place_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000002;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasFractional()) {
          setFractional(other.getFractional());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasPlace()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        if (!hasFractional()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object place_ = "";
      /**
       * <code>required string place = 1;</code>
       */
      public boolean hasPlace() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string place = 1;</code>
       */
      public java.lang.String getPlace() {
        java.lang.Object ref = place_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            place_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string place = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPlaceBytes() {
        java.lang.Object ref = place_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          place_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string place = 1;</code>
       */
      public Builder setPlace(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        place_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string place = 1;</code>
       */
      public Builder clearPlace() {
        bitField0_ = (bitField0_ & ~0x00000001);
        place_ = getDefaultInstance().getPlace();
        onChanged();
        return this;
      }
      /**
       * <code>required string place = 1;</code>
       */
      public Builder setPlaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        place_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string type = 2;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 2;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 2;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }

      private float fractional_ ;
      /**
       * <code>required float fractional = 3;</code>
       */
      public boolean hasFractional() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required float fractional = 3;</code>
       */
      public float getFractional() {
        return fractional_;
      }
      /**
       * <code>required float fractional = 3;</code>
       */
      public Builder setFractional(float value) {
        bitField0_ |= 0x00000004;
        fractional_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float fractional = 3;</code>
       */
      public Builder clearFractional() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fractional_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetFractionalInfoResp)
    }

    // @@protoc_insertion_point(class_scope:GetFractionalInfoResp)
    private static final com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp();
    }

    public static com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GetFractionalInfoResp>
        PARSER = new com.google.protobuf.AbstractParser<GetFractionalInfoResp>() {
      @java.lang.Override
      public GetFractionalInfoResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetFractionalInfoResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetFractionalInfoResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetFractionalInfoResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /**
   * Protobuf service {@code FractionalInfoService}
   */
  public static abstract class FractionalInfoService
      implements com.google.protobuf.Service {
    protected FractionalInfoService() {}

    public interface Interface {
      /**
       * <code>rpc GetFractionalInfo(.GetFractionalInfoReq) returns (.GetFractionalInfoResp);</code>
       */
      public abstract void getFractionalInfo(
          com.google.protobuf.RpcController controller,
          com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq request,
          com.google.protobuf.RpcCallback<com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new FractionalInfoService() {
        @java.lang.Override
        public  void getFractionalInfo(
            com.google.protobuf.RpcController controller,
            com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq request,
            com.google.protobuf.RpcCallback<com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp> done) {
          impl.getFractionalInfo(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getFractionalInfo(controller, (com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc GetFractionalInfo(.GetFractionalInfoReq) returns (.GetFractionalInfoResp);</code>
     */
    public abstract void getFractionalInfo(
        com.google.protobuf.RpcController controller,
        com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq request,
        com.google.protobuf.RpcCallback<com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.thinking.grpc.proto.StuFractionalProto.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getFractionalInfo(controller, (com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq)request,
            com.google.protobuf.RpcUtil.<com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.thinking.grpc.proto.StuFractionalProto.FractionalInfoService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getFractionalInfo(
          com.google.protobuf.RpcController controller,
          com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq request,
          com.google.protobuf.RpcCallback<com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp.class,
            com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp getFractionalInfo(
          com.google.protobuf.RpcController controller,
          com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp getFractionalInfo(
          com.google.protobuf.RpcController controller,
          com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoReq request)
          throws com.google.protobuf.ServiceException {
        return (com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.thinking.grpc.proto.StuFractionalProto.GetFractionalInfoResp.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:FractionalInfoService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetFractionalInfoReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetFractionalInfoReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetFractionalInfoResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetFractionalInfoResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033FractionalInfoService.proto\"3\n\024GetFrac" +
      "tionalInfoReq\022\r\n\005place\030\001 \002(\t\022\014\n\004type\030\002 \002" +
      "(\t\"H\n\025GetFractionalInfoResp\022\r\n\005place\030\001 \002" +
      "(\t\022\014\n\004type\030\002 \002(\t\022\022\n\nfractional\030\003 \002(\0022[\n\025" +
      "FractionalInfoService\022B\n\021GetFractionalIn" +
      "fo\022\025.GetFractionalInfoReq\032\026.GetFractiona" +
      "lInfoRespB5\n\027com.thinking.grpc.protoB\022St" +
      "uFractionalProtoH\001\210\001\001\240\001\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetFractionalInfoReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetFractionalInfoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetFractionalInfoReq_descriptor,
        new java.lang.String[] { "Place", "Type", });
    internal_static_GetFractionalInfoResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetFractionalInfoResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetFractionalInfoResp_descriptor,
        new java.lang.String[] { "Place", "Type", "Fractional", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
